table:
  name: app_settings
  schema: public
select_permissions:
  - role: developer
    permission:
      columns: '*'
      filter: {}
      allow_aggregations: true
    comment: Developer role has full select access
  - role: consultant
    permission:
      columns:
        - id
        - permissions
      filter: {}
    comment: All roles can view app settings
  - role: manager
    permission:
      columns:
        - id
        - permissions
      filter: {}
    comment: All roles can view app settings
  - role: org_admin
    permission:
      columns:
        - id
        - permissions
      filter: {}
    comment: Org admins can view app settings
  - role: viewer
    permission:
      columns:
        - id
        - permissions
      filter: {}
    comment: All roles can view app settings
insert_permissions:
  - role: developer
    permission:
      check: {}
      columns: '*'
    comment: Developer role has full insert access
update_permissions:
  - role: developer
    permission:
      columns: '*'
      filter: {}
      check: {}
    comment: Developer role has full update access
  - role: org_admin
    permission:
      columns:
        - permissions
      filter: {}
      check: {}
    comment: Only org admins can update app settings
delete_permissions:
  - role: developer
    permission:
      filter: {}
    comment: Developer role has full delete access
