/**
 * THIS FILE IS AUTO-GENERATED - DO NOT EDIT MANUALLY
 * 
 * SOC2 Compliant GraphQL Operations - Client Preset v4.0
 * Security Classifications Applied:
 * - CRITICAL: Auth, user roles, financial data - Requires admin access + MFA
 * - HIGH: PII, client data, employee info - Requires role-based access
 * - MEDIUM: Internal business data - Requires authentication
 * - LOW: Public/aggregate data - Basic access control
 * 
 * Compliance Features:
 * ✓ Role-based access control (RBAC)
 * ✓ Audit logging integration
 * ✓ Data classification enforcement
 * ✓ Permission boundary validation
 * ✓ Automatic domain isolation and exports
 * ✓ Client Preset v4.8+ for optimal type safety
 * ✓ Zero type conflicts with modern codegen
 * 
 * Generated: 2025-06-26T08:26:40.499Z
 * Schema Version: Latest from Hasura
 * CodeGen Version: Client Preset v4.0
 */

// Central export aggregator for GraphQL operations using Client Preset

// Shared operations and hooks (generated by client preset)
export * from './generated/';

// Domain-specific exports available at:
// import { useGetUserQuery } from '../../../domains/users/graphql/generated/';
// import { useCreateNoteQuery } from '../../../domains/notes/graphql/generated/';
// Each domain now uses client preset for zero-conflict type generation

// Common utilities
export { gql } from './generated/';
