# Hasura Configuration
# This file defines environment-specific configurations for Hasura

version: 3
endpoint: https://hasura.bytemy.com.au
admin_secret: 3w+sHTuq8wQwddK4xyWO5LDeRH+anvJoFVyOMvtq8Lo=
metadata_directory: metadata
migrations_directory: migrations
seeds_directory: seeds
actions:
  # Environment variables for action URLs
  # These will be replaced with actual values based on the environment
  ACTION_BASE_ENDPOINT: ${ACTION_BASE_ENDPOINT}
